/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODIGOS;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Ibyte
 */
public class Tela extends javax.swing.JFrame {
    
    public static String nome = JOptionPane.showInputDialog(null,"Qual seu nome ?","AI_3",JOptionPane.QUESTION_MESSAGE);
    
    public Timer timer;
    
    public String tela_da_conversa;
    public String relogio;
    public String segundos;
    public String minutos;
    public String horas;
    
    public int contador_de_linhas = 0;
    public static int linhas;
    public int contador;
    public int minutos_int;
    public int horas_int;
    
    /**
     * Creates new form TelaPrincipal
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTO_CONVERSA = new javax.swing.JTextArea();
        TEXTO_USUARIO = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabelTimerLoggedIn = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TEXTO_CONVERSA.setEditable(false);
        TEXTO_CONVERSA.setColumns(20);
        TEXTO_CONVERSA.setRows(5);
        jScrollPane1.setViewportView(TEXTO_CONVERSA);

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabelTimerLoggedIn.setText("Time Logged In :");
        jLabelTimerLoggedIn.setPreferredSize(new java.awt.Dimension(57, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(TEXTO_USUARIO)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelTimerLoggedIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_send)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clear)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEXTO_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_send)
                    .addComponent(btn_clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTimerLoggedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Diretorio.pastaPrincipal();
        
        ////////////////////////////////////////////////////////////////////////
        int delay = 1000;//1000
        //
        timer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                contador++;
                
                /////////////////////////SEGUNDOS/////////////////////////
                if(contador < 10){
                    segundos = "0"+contador;
                }
                if(contador > 9){
                    segundos = ""+contador;
                }
                if(contador == 60){
                    contador = 0;
                    segundos = "0"+contador;
                    minutos_int++;
                }
                /////////////////////////SEGUNDOS/////////////////////////
                /////////////////////////MINUTOS/////////////////////////
                if(minutos_int == 0){
                    minutos = "00";
                }
                if(minutos_int < 10){
                    minutos = "0"+minutos_int;
                }
                if(minutos_int > 9){
                    minutos = ""+minutos_int;
                }
                if(minutos_int == 60){
                    minutos_int = 0;
                    minutos = "0"+minutos_int;
                    horas_int++;
                }
                /////////////////////////MINUTOS/////////////////////////
                /////////////////////////HORAS/////////////////////////
                if(horas_int == 0){
                    horas = "00";
                }
                if(horas_int < 10){
                    horas = "0"+horas_int;
                }
                if(horas_int > 9){
                    horas = ""+horas_int;
                }
                if(horas_int == 24){
                    horas_int = 0;
                    horas = "0"+horas_int;
                }
                /////////////////////////HORAS/////////////////////////
                
                jLabelTimerLoggedIn.setText("Time Logged In : "+horas+":"+minutos+":"+segundos);
            }
        });
        
        timer.start();
        
        ////////////////////////////////////////////////////////////////////////
        
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
            .addKeyEventDispatcher(new KeyEventDispatcher() {
                @Override
                public boolean dispatchKeyEvent(KeyEvent event) {
                    if(event.getID() == KeyEvent.KEY_RELEASED 
                       && event.getKeyCode() == KeyEvent.VK_ENTER){
                        btn_sendActionPerformed(null);
                           return true;
                     }
                     return false;
                }
        });
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        
        linhas = TEXTO_CONVERSA.getLineCount();
        
        if(contador_de_linhas == 0 && linhas == 1){
            linhas = 1;
            contador_de_linhas++;
        }else
        if(contador_de_linhas != 0 && linhas == 1){
            linhas = 2;
        }else{
            linhas = TEXTO_CONVERSA.getLineCount()+1;
            contador_de_linhas = 0;
        }
        
        tela_da_conversa = TEXTO_CONVERSA.getText();
        
        if(!TEXTO_USUARIO.getText().equals("") && tela_da_conversa.equals("")){
            TEXTO_CONVERSA.setText(""+tela_da_conversa+nome+" : "+TEXTO_USUARIO.getText());
        }
        else
        if(!TEXTO_USUARIO.getText().equals("") &&  !tela_da_conversa.equals("")){
            TEXTO_CONVERSA.setText(""+tela_da_conversa+"\n"+nome+" : "+TEXTO_USUARIO.getText());
        }
        
        try {
            CODIGOS.Verificador.resposta(TEXTO_USUARIO.getText());
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TEXTO_USUARIO.setText("");
        
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        
        TEXTO_CONVERSA.setText("");
        
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea TEXTO_CONVERSA;
    public static javax.swing.JTextField TEXTO_USUARIO;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelTimerLoggedIn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}